# Generated by Django 4.2.16 on 2025-06-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moons', '0019_oreprice_goo_only_oretaxrates_ignore_ores_in_refine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moonrental',
            name='price',
            field=models.BigIntegerField(default=100000000),
        ),
    ]
