# Generated by Django 4.2.16 on 2026-02-27 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("moons", "0020_alter_moonrental_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frackore",
            name="ore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eve_sde.itemtype"
            ),
        ),
        migrations.AlterField(
            model_name="miningobservation",
            name="moon",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eve_sde.moon",
            ),
        ),
        migrations.AlterField(
            model_name="miningobservation",
            name="type_name",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="miningtax",
            name="constellation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_constellation",
                to="eve_sde.constellation",
            ),
        ),
        migrations.AlterField(
            model_name="miningtax",
            name="moon",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_moon",
                to="eve_sde.moon",
            ),
        ),
        migrations.AlterField(
            model_name="miningtax",
            name="region",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_region",
                to="eve_sde.region",
            ),
        ),
        migrations.AlterField(
            model_name="miningtax",
            name="system",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_system",
                to="eve_sde.solarsystem",
            ),
        ),
        migrations.AlterField(
            model_name="moonfrack",
            name="moon_name",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eve_sde.moon",
            ),
        ),
        migrations.AlterField(
            model_name="moonrental",
            name="moon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eve_sde.moon"
            ),
        ),
        migrations.AlterField(
            model_name="oreprice",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ore_price",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="oretax",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ore_tax",
                to="eve_sde.itemtype",
            ),
        ),
    ]
