# Generated by Django 5.2.12 on 2026-03-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moons", "0021_alter_frackore_ore_alter_miningobservation_moon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oretaxrates",
            name="tax_on_base_ore_value",
            field=models.BooleanField(
                default=False,
                help_text="Calculate Tax on the base ore value for all variants of an ore.",
            ),
        ),
    ]
