# Generated by Django 4.2.29 on 2026-10-02 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("moons", "0022_oretaxrates_tax_on_base_ore_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoonScan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField()),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan",
                        to="eve_sde.moon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoonScanOre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fraction", models.DecimalField(decimal_places=12, max_digits=13)),
                (
                    "ore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ores",
                        to="moons.moonscan",
                    ),
                ),
            ],
            options={
                "unique_together": {("scan", "ore")},
            },
        ),
    ]
