# Generated by Django 4.2.29 on 2026-10-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moons", "0023_moon_scans"),
    ]

    operations = [
        migrations.AddField(
            model_name="oretaxrates",
            name="show_in_moon_values",
            field=models.BooleanField(
                default=False,
                help_text="Offer this profile when valuing scanned moons and suggesting rental prices.",
            ),
        ),
    ]
