# Generated by Django 4.2.29 on 2026-10-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moons", "0024_oretaxrates_show_in_moon_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="oretaxrates",
            name="drill_m3_per_hour",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Moon value extraction rate. Blank uses MOONS_DRILL_M3_PER_HOUR (40,000 for an Athanor/Tatara). A Metenox harvests 30,000 at 40% refine, moon materials only.",
                null=True,
            ),
        ),
    ]
