# Generated by Django 4.2.29 on 2026-10-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moons", "0025_oretaxrates_drill_m3_per_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="oretaxrates",
            name="rent_minimum",
            field=models.BigIntegerField(
                default=0, help_text="Rent commands: lowest rent suggested, in ISK."
            ),
        ),
        migrations.AddField(
            model_name="oretaxrates",
            name="rent_profit_share",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Rent commands: percent of (tax - fuel) charged as rent.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="oretaxrates",
            name="rent_subtract_metenox_fuel",
            field=models.BooleanField(
                default=False,
                help_text="Rent commands: subtract 30 days of Metenox fuel from the tax.",
            ),
        ),
    ]
