# Generated by Django 4.2.29 on 2026-10-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moons", "0026_oretaxrates_rent_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalRepricing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(
                        default=False,
                        help_text="Only post the projected prices: change no rentals and message no renters.",
                    ),
                ),
                (
                    "notify_renters",
                    models.BooleanField(
                        default=True,
                        help_text="DM each renter their moons' new prices (needs the Discord bot).",
                    ),
                ),
                (
                    "channel_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord channel ID for the run summary (needs the Discord bot).",
                        null=True,
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "rental repricing settings",
                "verbose_name_plural": "rental repricing settings",
            },
        ),
        migrations.AddField(
            model_name="moonrental",
            name="reprice_method",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The reprice_rentals task sets the price to this ore tax's suggested rent. Empty: never repriced.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="moons.oretaxrates",
            ),
        ),
    ]
