# Generated by Django 4.2.29 on 2026-10-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moons", "0027_rental_reprice_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="miningtax",
            name="flat_tax_on_base_ore_value",
            field=models.BooleanField(
                default=False,
                help_text="Flat rate only: tax every variant of an ore (e.g. jackpot moon ore) at its base ore's value. Variable rates use their Ore Tax Rates' 'Tax on base ore value' instead.",
            ),
        ),
    ]
