# Generated by Django 4.2.29 on 2026-10-05 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("moons", "0028_miningtax_flat_tax_on_base_ore_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoonAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, default="")),
                ("changed_at", models.DateTimeField()),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_availability",
                        to="eve_sde.moon",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "moon availability",
            },
        ),
    ]
